config/routes.rb
Rails.application.routes.draw do

  unless  Gem::Specification::find_all_by_name('route_translator').any?

    # normal translation scoping
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      ##### ACCESS CONTROL
      # legacy routes. Pointing to new pathway. Keep them. They are semantically sound.
      # still used in this gem.
      get 'signup', to: 'reception#email_input', as: 'signup'
      get 'login', to: 'reception#email_input', as: 'login'
      get 'logout', to: 'reception#disconnect', as: 'logout'
      # New access control pathway
      get '/reception', to: 'reception#email_input', as: 'email_input'
      post '/parse_email', to: 'reception#parse_email'
      get '/email_validation', to: 'reception#email_validation'
      get '/create_your_password', to: 'reception#create_your_password'
      post '/password_creation/:id', to: 'reception#password_creation', as: 'password_creation'
      get '/enter_your_password', to: 'reception#enter_your_password'
      post '/password_checking/:id', to: 'reception#password_checking', as: 'password_checking'
      get '/i_forgot_my_password', to: 'reception#i_forgot_my_password'
      post '/request_new_password', to: 'reception#request_new_password'
      get '/change_your_password', to: 'reception#change_your_password'
      post '/password_reset/:id', to: 'reception#password_reset', as: 'password_reset'
      get '/disconnect', to: 'reception#disconnect'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      ##### ACCESS CONTROL
      # legacy routes. Pointing to new pathway. Keep them. They are semantically sound.
      # still used in this gem.
      get 'signup', to: 'reception#email_input', as: 'signup'
      get 'login', to: 'reception#email_input', as: 'login'
      get 'logout', to: 'reception#disconnect', as: 'logout'
      # New access control pathway
      get '/reception', to: 'reception#email_input', as: 'email_input'
      post '/parse_email', to: 'reception#parse_email'
      get '/email_validation', to: 'reception#email_validation'
      get '/create_your_password', to: 'reception#create_your_password'
      post '/password_creation/:id', to: 'reception#password_creation', as: 'password_creation'
      get '/enter_your_password', to: 'reception#enter_your_password'
      post '/password_checking/:id', to: 'reception#password_checking', as: 'password_checking'
      get '/i_forgot_my_password', to: 'reception#i_forgot_my_password'
      post '/request_new_password', to: 'reception#request_new_password'
      get '/change_your_password', to: 'reception#change_your_password'
      post '/password_reset/:id', to: 'reception#password_reset', as: 'password_reset'
      get '/disconnect', to: 'reception#disconnect'
    end

  end

end

app/views/shared/_embedded_access_control.html.erb
<div class="embedded-access-control">
  <%= render 'reception/email_input_form' %>
</div>

app/views/shared/_embedded_login_module.html.erb
<ul class="nav nav-tabs" id="loginTab">
	<li class="active"><a href="#login-tab" data-toggle="tab"><%= t('authentication.login_now') %></a></li>
	<li><a href="#signup-tab" data-toggle="tab"><%= t('authentication.create_account') %></a></li>
</ul>
 
<div class="tab-content">
	<div class="tab-pane active" id="login-tab">
		<%= render 'sessions/form' %>
	</div>
	<div class="tab-pane" id="signup-tab">
		<%= render 'users/form', user: User.new %>
	</div>
</div>

app/views/shared/_login_info.html.erb
<p class="login-info">
	<% if current_user %>
	  <strong><%= current_user.email %></strong> <%= link_to t('authentication.logout'), logout_path, class: 'btn btn-mini' %>
	<% else %>
	  <%= link_to t('authentication.login_now'), login_path, class: 'btn btn-mini' %> or <%= link_to "Sign Up", signup_path, class: 'btn btn-mini' %>
	<% end %>
</p>

app/views/shared/_login_info_for_navbar.html.erb
<% if current_user %>
  <ul class="nav navbar-nav navbar-right navbar-login-info">
    <li class='dropdown'>
    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<%= current_user.email %> <b class="caret"></b></a>
    	<ul class="dropdown-menu">
        <%= content_tag :li, link_to("<span class=\"glyphicon glyphicon-user\"></span>&nbsp;profile".html_safe, profile_path) %>
    		<%= content_tag :li, link_to("<span class=\"glyphicon glyphicon-off\"></span>&nbsp;#{t('logout').downcase}".html_safe, logout_path) %>
    	</ul>
    </li>
  </ul>
<% else # not logged in %>
  <ul class="nav navbar-nav navbar-right">
    <li><%= link_to(t('authentication.login_now'), email_input_path) %></li>
  </ul>
<% end %>

app/views/shared/_login_info_for_sidebar.html.erb
<% if current_user %>
	<div class="btn-group">
		<br />
		<a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %>&nbsp;<span class="caret"></span></a>
		<ul class="dropdown-menu">
			<%= content_tag :li, link_to(t('logout'), logout_path) %>
		</ul>
	</div>
<% else %>
	<p><br /><%= link_to "<span class='glyphicon glyphicon-off'></span> #{t('authentication.login_now')}".html_safe, login_path, class: 'btn btn-default' %></p>
<% end %>

app/views/shared/_other_name_label.html.erb
nickname or other name