config/routes.rb
Rails.application.routes.draw do

  unless  Gem::Specification::find_all_by_name('route_translator').any?

    # normal translation scoping
    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      ##### ACCESS CONTROL
      # legacy routes. Pointing to new pathway. Keep them. They are semantically sound.
      # still used in this gem.
      get 'signup', to: 'reception#email_input', as: 'signup'
      get 'login', to: 'reception#email_input', as: 'login'
      get 'logout', to: 'reception#disconnect', as: 'logout'
      # New access control pathway
      get '/reception', to: 'reception#email_input', as: 'email_input'
      post '/parse_email', to: 'reception#parse_email'
      get '/email_validation', to: 'reception#email_validation'
      get '/create_your_password', to: 'reception#create_your_password'
      post '/password_creation/:id', to: 'reception#password_creation', as: 'password_creation'
      get '/enter_your_password', to: 'reception#enter_your_password'
      post '/password_checking/:id', to: 'reception#password_checking', as: 'password_checking'
      get '/i_forgot_my_password', to: 'reception#i_forgot_my_password'
      post '/request_new_password', to: 'reception#request_new_password'
      get '/change_your_password', to: 'reception#change_your_password'
      post '/password_reset/:id', to: 'reception#password_reset', as: 'password_reset'
      get '/disconnect', to: 'reception#disconnect'
    end

  else # special routing for localized routes via the route_translator gem

    localized do
      ##### ACCESS CONTROL
      # legacy routes. Pointing to new pathway. Keep them. They are semantically sound.
      # still used in this gem.
      get 'signup', to: 'reception#email_input', as: 'signup'
      get 'login', to: 'reception#email_input', as: 'login'
      get 'logout', to: 'reception#disconnect', as: 'logout'
      # New access control pathway
      get '/reception', to: 'reception#email_input', as: 'email_input'
      post '/parse_email', to: 'reception#parse_email'
      get '/email_validation', to: 'reception#email_validation'
      get '/create_your_password', to: 'reception#create_your_password'
      post '/password_creation/:id', to: 'reception#password_creation', as: 'password_creation'
      get '/enter_your_password', to: 'reception#enter_your_password'
      post '/password_checking/:id', to: 'reception#password_checking', as: 'password_checking'
      get '/i_forgot_my_password', to: 'reception#i_forgot_my_password'
      post '/request_new_password', to: 'reception#request_new_password'
      get '/change_your_password', to: 'reception#change_your_password'
      post '/password_reset/:id', to: 'reception#password_reset', as: 'password_reset'
      get '/disconnect', to: 'reception#disconnect'
    end

  end

end

app/controllers/reception_controller.rb
class ReceptionController < ApplicationController

  # TODO change email address - may be a profile feature in tkh_mailing_list
  # TODO change password -              ""
  # TODO localize the whole process

  before_action :set_target_page, only: [ :email_input, :parse_email, :email_validation, :create_your_password, :enter_your_password, :disconnect ]

  def email_input
  end

  def parse_email
    unless params[:user][:email].blank?
      @user = User.find_by(email: params[:user][:email])
      if @user.blank? # first take care of the easy case with a completely new user
        # create new record
        @user = User.new(user_params)
        if @user.save
          send_validation_email
          @status = 'email_validation'
          respond_to do |format|
            format.html { flash[:notice] = "Your record has been successfully created." }
            format.js {}
          end
        else # problem saving new user record for some reason
          @status = 'no_user_save'
          respond_to do |format|
            format.html { flash[:alert] = "We had problems creating your record. Please try again. Make sure the email address is valid." }
            format.js {}
          end
        end
      else # the email address was already in the database
        # Returning user pathway goes here
        if @user.email_validated? && @user.has_a_password?
          @status = 'enter_password'
          respond_to do |format|
            format.html { redirect_to enter_your_password_path(auth_token: @user.auth_token) }
            format.js {}
          end
        elsif @user.email_validated? && !@user.has_a_password? # doesn't have a password
          # User needs to securily create a password
          send_password_creation_security_email
          # show screen to user with notice about password confirmation email
          @status = 'password_confirmation'
          respond_to do |format|
            format.html { flash[:notice] = "There is 1 last step!" }
            format.js {}
          end
        elsif !@user.email_validated?
          send_validation_email
          # show screen to user with notice about email validation
          @status = 'email_validation'
          respond_to do |format|
            format.html { flash[:notice] = "For your security, we need to verify your email address." }
            format.js {}
          end
        end
      end
    else # email is blank
      @status = 'blank_email'
      respond_to do |format|
        format.html { flash[:alert] = "Your email address cannot be blank." }
        format.js {}
      end
    end
  end

  def email_validation
    @user = User.where(email_validation_token: params[:token]).first
    if @user && @user.email_validation_token_sent_at >= Time.zone.now - 1.hour # still valid token
      @user.email_validated = true
      @user.save
      unless @user.has_a_password?
        set_password_creation_token
        flash[:notice] = "Your email has been validated. There is 1 last step!"
        redirect_to create_your_password_path(password_creation_token: @user.password_creation_token)
      else # the user has a password
        redirect_to enter_your_password_path(auth_token: @user.auth_token)
      end
    elsif @user && @user.email_validation_token_sent_at <= Time.zone.now - 1.hour # expiredd token
      redirect_to email_input_url, alert: "Your verification token was created over an hour ago. Please restart the process."
    else
      redirect_to email_input_url, alert: "We were unable to validate your email. Please try again and make sure you are using a valid email address."
    end
  end

  def create_your_password
    @user = User.find_by(password_creation_token: params[:password_creation_token])
    if @user.blank?
      redirect_to email_input_url, alert: "We were unable to find the record in the database. Please restart the process and make sure you are using a valid email address."
    end
  end

  def password_creation
    @user = User.find(params[:id])
    unless @user.blank?
      if !params[:user][:password].blank? && (params[:user][:password] == params[:user][:password_confirmation])
        if @user.password_creation_token_sent_at >= Time.zone.now - 1.hour # still valid token
          if @user.update(user_params)
            login_the_user
            flash[:notice] = "Your new password was created and you have been logged in."
            redirect_to session[:target_page] || root_path
            destroy_target_page
          else # did not update ?!?
            flash[:alert] = "Some problems occurred while trying to create your password"
            render create_your_password
          end
        else # the token has expired
          redirect_to email_input_path, alert: 'Sorry, your password_creation_token has expired. To protect your privacy and ensure your security, we need to ask you to start the process over again. The token, when created, expires after 1 hour!'
        end
      else # password is blank or password and password_confirmation don't match
         redirect_to ( request.env["HTTP_REFERER"].present? ? :back : root_path ), alert: 'Your password cannot be blank and the password should be identical to the password confirmation. Please try again.'
      end
    else # @user is blank
      redirect_to email_input_path, alert: 'We could not find this user record in our database. Please start the process over.'
    end
  end

  def enter_your_password
    @user = User.find_by(auth_token: params[:auth_token])
  end

  def password_checking
    @user = User.find(params[:id])
    if @user

      # Update names if necessary
      if params[:user][:first_name].present? || params[:user][:last_name].present? || params[:user][:other_name].present?
        @user.first_name = params[:user][:first_name]
        @user.last_name = params[:user][:last_name]
        @user.other_name = params[:user][:other_name]
        @user.save
      end

      if @user.email_validated?
        if @user.authenticate(params[:user][:password])
          login_the_user
          flash[:notice] = t('authentication.login_confirmation')
          redirect_user_upon_successful_login
          destroy_target_page
        else # most likely wrong password
          flash.now.alert = t('authentication.warning.email_or_password_invalid')
          render "enter_your_password"
        end
      else # email not validated
        send_validation_email
        redirect_to root_path, alert: 'Our records show that your email address has not been validated. We need you to do so before letting your log in. Please check your email inbox or spam folder for an validation email.'
      end
    else # we can't find the user in the database
      flash[:alert] = "We were unable to find your email in the database. Please try again and make sure you are using a valid email address."
      redirect_to email_input_url
    end
  end

  def i_forgot_my_password
  end

  def request_new_password
    @user = User.find_by(email: params[:user][:email])
    if @user
      send_new_password_request_email
      # show confirmation screen
    else
      redirect_to i_forgot_my_password_path, alert: "We could not find a user with this email address: #{params[:user][:email]}. Please try again."
    end
  end

  def change_your_password
    @user = User.find_by(password_reset_token: params[:password_reset_token])
    if @user.blank?
      redirect_to email_input_url, alert: "We were unable to find the record in the database. Please restart the process and make sure you are using a valid email address."
    end
  end

  def password_reset
    @user = User.find(params[:id])
    if @user.present?
      if params[:user][:password].present? && (params[:user][:password] == params[:user][:password_confirmation])
        if @user.password_reset_sent_at >= Time.zone.now - 1.hour # still valid token
          if @user.update(user_params)
            login_the_user
            flash[:notice] = "Your password was changed and you have been logged in."
            redirect_to session[:target_page] || root_path
            destroy_target_page
          else # did not update ?!?
            flash[:alert] = "Some problems occurred while trying to change your password. Please try again."
            render change_your_password
          end
        else # the token has expired
          redirect_to email_input_path, alert: 'Sorry, your password_reset_token has expired. To protect your privacy and ensure your security, we need to ask you to start the process over again. The token, when created, expires after 1 hour!'
        end
      else # password is blank or password and password_confirmation don't match
        redirect_to :back, alert: 'Your password cannot be blank and the password should be identical to the password confirmation. Please try again.'
      end
    else # @user is blank
      redirect_to email_input_path, alert: 'We could not find this user record in our database. Please start the process over.'
    end
  end

  def disconnect
    cookies.delete(:auth_token)
    redirect_to root_url, notice: t('authentication.logout_confirmation')
    destroy_target_page
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit :email, :password, :password_confirmation, :first_name, :last_name, :other_name
  end

  def set_target_page
    session[:target_page] = request.referer unless session[:target_page]
  end

  def destroy_target_page
    session[:target_page] = nil
  end

  def send_validation_email
    set_email_validation_token
    ReceptionMailer.verification_email(@user).deliver
  end

  def set_email_validation_token
    @user.generate_token(:email_validation_token)
    @user.email_validation_token_sent_at = Time.zone.now
    @user.save
  end

  def send_password_creation_security_email
    set_password_creation_token

app/views/reception/_admin_context_menu.html.erb
<% if administrator? %>

  <% content_for :admin_context_menu do %>

    <h2><%= t('admin_section') %></h2>
    <ul class="list-group">
      <li class="list-group-item"><%= link_to t('admin_panel'), members_path %></li>
      <%= content_tag :li, link_to( "#{t('activerecord.models.comments').capitalize} <span class='badge'>#{Comment.pending.count}</span>".html_safe, pending_comments_path ), class: 'list-group-item' if Comment.pending.count > 0 %>
      <% if controller.action_name == 'show' %>
      <% end %>
    </ul>

  <% end -%>

<% end -%>

app/views/reception/_email_input_form.html.erb
<% submit_message = 'proceed' if submit_message.blank? %>

<%= simple_form_for User.new, url: parse_email_path, html: { id: 'email-input-form' }, remote: true, method: 'post' do |f| %>
  <%= f.error_notification %>

  <% # had to remove autofocus: true because when form was embedded at the bottom of a page, the browser would scroll all the way down to the field in the page. %>
  <%= f.input :email, label: 'Please enter your email address' %>
  <br />
  <%= f.button :submit, submit_message, :class => 'btn btn-primary' %>
<% end %>

app/views/reception/_enter_your_password_form.html.erb
<%= simple_form_for @user, :url => password_checking_path(@user.id), id: 'enter-you-password-form', method: :post do |f| %>
  <%= f.error_notification %>

  <p>Email: <strong><%= @user.email %></strong>. (<small><%= link_to "want to use a different email?", email_input_path %></small>)</p>
  <%= f.input :password, autofocus: true, hint: link_to("forgot your password?", i_forgot_my_password_path) %>
  <br />
  <%= f.input_field :remember_me, as: :boolean, boolean_style: :inline, checked: 'checked' %> &nbsp;remember me
  <br /><br />

  <% unless @user.visible_name_present? %>
    <p>Please take a few seconds to enter your name.</p>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <% # i want certain sites to use a different label for this. They can add a partial in host app. %>
    <%= f.input :other_name, label: render('shared/other_name_label') %><br />
  <% end %>

  <%= f.submit 'log in!', class: 'btn btn-primary' %>
<% end %>

app/views/reception/_enter_your_password_form.js.erb
<%= simple_form_for @user, :url => password_checking_path(@user.id), id: 'enter-you-password-form', method: :post do |f| %>
  <%= f.error_notification %>

  <p>Email: <strong><%= @user.email %></strong>. (<small><%= link_to "want to use a different email?", email_input_path %></small>)</p>
  <%= f.input :password, autofocus: true, hint: link_to("forgot your password?", i_forgot_my_password_path) %>
  <br />
  <%= f.input_field :remember_me, as: :boolean, boolean_style: :inline, checked: 'checked' %> &nbsp;remember me
  <br /><br />

  <% unless @user.visible_name_present? %>
    <p>Please take a few seconds to enter your name.</p>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <% # i want certain sites to use a different label for this. They can add a partial in host app. %>
    <%= f.input :other_name, label: render('shared/other_name_label') %><br />
  <% end %>

  <%= f.submit 'log in!', class: 'btn btn-primary' %>
<% end %>

app/views/reception/change_your_password.html.erb
<% content_for :meta_title, 'Change your password' %>
<% content_for :meta_description, "You need to create a new password so that we can log you in." %>

<h1>Change Your Password</h1>

<%= simple_form_for @user, :url => password_reset_path(@user.id), method: :post do |f| %>
  <%= f.error_notification %>

  <p>Email: <strong><%= @user.email %></strong>. (<small><%= link_to "want to use a different email?", email_input_path %></small>)</p>

  <%= f.input :password, autofocus: true %>
  <%= f.input :password_confirmation %>
  <br />
  <%= f.input_field :remember_me, as: :boolean, boolean_style: :inline %> &nbsp;yes, remember me
  <br /><br />
  <%= f.submit 'change your password and log in!', class: 'btn btn-primary' %>
<% end %>

app/views/reception/create_your_password.html.erb
<% content_for :meta_title, 'Create your password' %>
<% content_for :meta_description, "You need to create a password so that we can log you in." %>

<h1>Create Your Password & We'll Log You Right In</h1>

<%= simple_form_for @user, :url => password_creation_path(@user.id), method: :post do |f| %>
  <%= f.error_notification %>

  <p>Email: <strong><%= @user.email %></strong>. (<small><%= link_to "want to use a different email?", email_input_path %></small>)</p>

  <%= f.input :password, autofocus: true %>
  <%= f.input :password_confirmation %>
  <br />
  <%= f.input_field :remember_me, as: :boolean, boolean_style: :inline, checked: 'checked' %> &nbsp;remember me
  <br /><br />

  <% unless @user.visible_name_present? %>
    <p>Please take a few seconds to enter your name.</p>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <% # i want certain sites to use a different label for this. They can add a partial in host app. %>
    <%= f.input :other_name, label: render('shared/other_name_label') %><br />
  <% end %>

  <%= f.submit 'Create password and log in!', class: 'btn btn-primary' %>
<% end %>

app/views/reception/email_input.html.erb
<% content_for :meta_title, 'Login with your email' %>
<% content_for :meta_description, "We need your email address to initiate the login or account creation procedure." %>

<% unless current_user # most folks coming to this page should not be logged in %>

  <h1 id="login-header">Login</h1>

  <%= render 'email_input_form' %>

<% else # the user is already logged in %>

  <h1>You are already logged in</h1>
  <p>This is the login page but it appears that you are already logged in with this address: <strong><%= current_user.email %></strong></p>

  <p><%= link_to 'go to home page', root_path, class: 'btn btn-primary' %><%= link_to 'logout', disconnect_path, class: 'btn btn-default' %></p>

<% end %>

<%= render 'admin_context_menu' %>
<%# partial in tkh_menus gem or has to be added in host app %>
<%= render './shared/menus' %>

app/views/reception/enter_your_password.html.erb
<% content_for :meta_title, 'Enter your password and log in!' %>
<% content_for :meta_description, "Enter your password to log in." %>

<h1>Enter Your Password & We'll Log You Right In</h1>

<%= render 'enter_your_password_form' %>

app/views/reception/i_forgot_my_password.html.erb
<h1>Forgot your password?</h1>

<%= simple_form_for User.new, :url => request_new_password_path, method: :post do |f| %>
  <%= f.error_notification %>

  <%= f.input :email, autofocus: true, hint: "We'll send an email to this address." %>
  <%= f.submit 'let me set a new password!', class: 'btn btn-primary' %>
<% end %>

app/views/reception/parse_email.html.erb
<% if @status == 'email_validation' %>

  <% content_for :meta_title, 'Email Confirmation' %>
  <% content_for :meta_description, "An email was just sent. Please check your inbox." %>
  <h1>A Validation Email is Coming</h1>
  <p>We've just sent an email to <strong><%= @user.email %></strong>. Please check your inbox or spam folder.</p>

<% elsif @status == 'password_confirmation' %>

  <% content_for :meta_title, 'Password creation Email Confirmation' %>
  <% content_for :meta_description, "An email was just sent. Please check your inbox or your spam folder." %>
  <h1>A Password Creation Security Email is Coming</h1>
  <p>For your security we need to check that you truly are the owner of this account. Please check your <strong><%= @user.email %></strong> inbox or spam folder.</p>

<% end %>

app/views/reception/parse_email.js.erb
<% if @status == 'enter_password' %>

  $('h1#login-header').html('Please Enter Your Password');
  $('#email-input-form').replaceWith("<%= escape_javascript(render(:partial => 'reception/enter_your_password_form')) %>");
  $('h1').effect("highlight", { color: '#8D5530' }, 1000);
  $(".user_password").effect("highlight", { color: '#8D5530' }, 1000);
  $('input#user_password').focus();
  $('.alert-danger').slideUp(750);

<% elsif @status == 'email_validation' %>

  $('h1#login-header').html('A Validation Email is Coming');
  $('#email-input-form').replaceWith("<p class=\"validation-message\">We have sent you an email. Please check your inbox or your spam folder.</p>");
  $('h1').effect("highlight", { color: '#8D5530' }, 1000);
  $("p.validation-message").effect("highlight", { color: '#8D5530' }, 1000);
  $('.alert-danger').slideUp(750);

<% elsif @status == 'password_confirmation' %>

  $('h1#login-header').html('A Password Creation Security Email is Coming');
  $('#email-input-form').replaceWith("<p class=\"confirmation-message\">For your security we need to check that you truly are the owner of this account. Please check your inbox or spam folder.</p>");
  $('h1').effect("highlight", { color: '#8D5530' }, 1000);
  $("p.confirmation-message").effect("highlight", { color: '#8D5530' }, 1000);
  $('.alert-danger').slideUp(750);

<% elsif @status == 'blank_email' %>

  $('h1#login-header').after('<div class="alert alert-danger"><a class="close" data-dismiss="alert">×</a>The email address CANNOT be blank.</div>');
  $('.alert-danger').hide().slideDown(750);

<% elsif @status == 'no_user_save' %>

  $('h1#login-header').after('<div class="alert alert-danger"><a class="close" data-dismiss="alert">×</a>We had problems creating your record. Please try again. Make sure the email address is valid.</div>');
  $('.alert-danger').hide().slideDown(750);

<% end %>

app/views/reception/request_new_password.html.erb
<% content_for :meta_title, 'New Password Request Email Confirmation' %>
<% content_for :meta_description, "An email was just sent to enable you to get your new password. Please check your inbox." %>

<h1>Your New Password Request Email is Coming</h1>

<p>To enable you to reset your password we've just sent an email to <strong><%= @user.email %></strong>. Please check your inbox or spam folder.</p>